options:
  relay-port:
    type: int
    default: 9001
    description: "Weechat relay port"
  relay-password:
    type: string
    default: ""
    description: "Password for relay, blank to generate one automatically"
  enable-relay:
    type: boolean
    default: True
    descriptoin: "Enable weechat relay"
  user-config:
    type: string
    default: ""
    description: |
      Custom config for weechat. One command per line, ex:
      /server add freenode chat.freenode.net/6697 -ssl -autoconnect
  encfs-enabled:
    type: boolean
    default: False
    description: "Encrypt the weechat folder and logs at rest"
  encfs-password:
    type: string
    default: ""
    description: "Encryption password, must be provided if encryption is enabled"
#   string-option:
#     type: string
#     default: "Default Value"
#     description: "A short description of the configuration option"
#   boolean-option:
#     type: boolean
#     default: False
#     description: "A short description of the configuration option"
#   int-option:
#     type: int
#     default: 9001
#     description: "A short description of the configuration option"
